version: '3.8'

services:
  cache:
    container_name: nest-network-cache
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/docker/volumes/nest_redis_data:/data
